"""
nomes_pt.py — Traduções de nomes de autores e títulos de obras clássicas
para o português brasileiro, usadas ao servir catálogos ao frontend.
"""

# ── autores ───────────────────────────────────────────────────────────────────

AUTORES_PT: dict[str, str] = {
    # Gregos
    "Aeneas Tacticus":               "Eneias Tático",
    "Aeschines":                     "Ésquines",
    "Aeschylus":                     "Ésquilo",
    "Alcidamas":                     "Alcidamas",
    "Andocides":                     "Andócides",
    "Antiphon":                      "Antifonte",
    "Apollodorus":                   "Apolodoro",
    "Apollonius Rhodius":            "Apolônio de Rodes",
    "Appianus of Alexandria":        "Apiano de Alexandria",
    "Aretaeus of Cappadocia":        "Areteu da Capadócia",
    "Aristides, Aelius":             "Élio Aristides",
    "Aristophanes":                  "Aristófanes",
    "Arrian":                        "Arriano",
    "Athenaeus of Naucratis":        "Ateneu de Náucrates",
    "Athenagoras":                   "Atenágoras",
    "Bacchylides":                   "Baquílides",
    "Barnabae epistula":             "Epístola de Barnabé",
    "Bion of Phlossa":               "Bíon de Esmirna",
    "Chariton of Aphrodisias":       "Caríton de Afrodísias",
    "Claudius Ptolemaeus":           "Cláudio Ptolomeu",
    "Colluthus of Lycopolis":        "Coluto de Licópolis",
    "Demosthenes":                   "Demóstenes",
    "Dinarchus":                     "Dinarca",
    "Diodorus Siculus":              "Diodoro Sículo",
    "Diogenes Laertius":             "Diógenes Laércio",
    "Dionysius of Halicarnassus":    "Dionísio de Halicarnasso",
    "Epictetus":                     "Epicteto",
    "Euclid":                        "Euclides",
    "Euripides":                     "Eurípides",
    "Galen":                         "Galeno",
    "Harpocration":                  "Harpocrátion",
    "Heliodorus of Emesa":           "Heliodoro de Emesa",
    "Herodotus":                     "Heródoto",
    "Hesiod":                        "Hesíodo",
    "Hippolytus":                    "Hipólito",
    "Homer":                         "Homero",
    "Homeric Hymns":                 "Hinos Homéricos",
    "Hyperides":                     "Hipérides",
    "Isaeus":                        "Iseu",
    "Isocrates":                     "Isócrates",
    "Justin Martyr":                 "Justino Mártir",
    "Longinus":                      "Longino",
    "Longus":                        "Longo de Lesbos",
    "Lucian of Samosata":            "Luciano de Samósata",
    "Lycophron":                     "Licofrão",
    "Lycurgus":                      "Licurgo",
    "Lysias":                        "Lísias",
    "Marcus Aurelius":               "Marco Aurélio",
    "Moschus":                       "Mosco",
    "New Testament":                 "Novo Testamento",
    "Nonnus of Panopolis":           "Nono de Panópolis",
    "Oppian":                        "Opiano",
    "Oppian of Apamea":              "Opiano de Apameia",
    "Origen":                        "Orígenes",
    "Pausanias":                     "Pausânias",
    "Philostratus Sophista":         "Filóstrato Sofista",
    "Philostratus the Athenian":     "Filóstrato de Atenas",
    "Pindar":                        "Píndaro",
    "Plato":                         "Platão",
    "Plutarch":                      "Plutarco",
    "Polybius":                      "Políbio",
    "Pseudo-Plutarch":               "Pseudo-Plutarco",
    "Quintus Smyrnaeus":             "Quinto de Esmirna",
    "Scholia in Pindarum":           "Escólios a Píndaro",
    "Sophocles":                     "Sófocles",
    "Strabo":                        "Estrabão",
    "Tatianus":                      "Taciano",
    "Theocritus":                    "Teócrito",
    "Theophilus":                    "Teófilo",
    "Theophrastus":                  "Teofrasto",
    "Thucydides":                    "Tucídides",
    "Tryphiodorus":                  "Trifiodoro",
    "Xenophon":                      "Xenofonte",
    "Xenophon of Ephesus":           "Xenofonte de Éfeso",
    # Latinos
    "Agathemerus":                   "Agatêmero",
    "Agathias Scholasticus":         "Agátias Escolástico",
    "Ammianus Marcellinus":          "Amiano Marcelino",
    "Anna Comnena":                  "Ana Comnena",
    "Apuleius":                      "Apuleio",
    "Archimedes":                    "Arquimedes",
    "Athanasius":                    "Atanásio",
    "Ausonius, Decimus Magnus":      "Ausônio",
    "Boethius":                      "Boécio",
    "Catullus":                      "Catulo",
    "Celsus, Aulus Cornelius":       "Aulo Cornélio Celso",
    "Cicero, Marcus Tullius":        "Cícero",
    "Claudian":                      "Claudiano",
    "Columella, Lucius Junius Moderatus": "Columela",
    "Curtius Rufus, Quintus":        "Quinto Cúrcio Rufo",
    "Eusebius of Caesarea":          "Eusébio de Cesareia",
    "Florus, Lucius Annaeus":        "Floro",
    "Gellius, Aulus":                "Aulo Gélio",
    "Hegemonius":                    "Hegêmônio",
    "Horace":                        "Horácio",
    "Jerome, Saint":                 "São Jerônimo",
    "Julius Caesar":                 "Júlio César",
    "Juvenal":                       "Juvenal",
    "Lucan":                         "Lucano",
    "Lucretius":                     "Lucrécio",
    "Martial":                       "Marcial",
    "Martyrium Perpetuae et Felcitatis": "Martírio de Perpétua e Felicidade",
    "Minucius Felix, Marcus":        "Minúcio Félix",
    "Nepos, Cornelius":              "Cornélio Nepos",
    "Origen":                        "Orígenes",
    "Ovid":                          "Ovídio",
    "P. Vergilius Maro":             "Virgílio",
    "Persius":                       "Pérsio",
    "Petronius Arbiter":             "Petrônio",
    "Phaedrus":                      "Fedro",
    "Plautus, Titus Maccius":        "Plauto",
    "Pliny, the Elder":              "Plínio, o Velho",
    "Pliny, the Younger":            "Plínio, o Jovem",
    "Porphyrius":                    "Porfírio",
    "Propertius, Sextus":            "Propércio",
    "Prudentius":                    "Prudêncio",
    "Quintilian":                    "Quintiliano",
    "Quintus Tullius Cicero":        "Quinto Túlio Cícero",
    "Sallust":                       "Salústio",
    "Scriptores Historiae Augustae": "Escritores da História Augusta",
    "Seneca, Lucius Annaeus":        "Sêneca",
    "Seneca, Lucius Annaeus, 55 B.C.-ca. 39 A.D.": "Sêneca, o Velho",
    "Sextus Empiricus":              "Sexto Empírico",
    "Silius Italicus, Tiberius Catius": "Sílio Itálico",
    "Statius, P. Papinius (Publius Papinius)": "Estácio",
    "Suetonius":                     "Suetônio",
    "Tacitus, Cornelius":            "Tácito",
    "Terence":                       "Terêncio",
    "Tertullian":                    "Tertuliano",
    "Themistius":                    "Temístio",
    "Tibullus":                      "Tibulo",
    "Titus Livius (Livy)":           "Tito Lívio",
    "Valerius Flaccus, Gaius":       "Valério Flaco",
    "Valerius Maximus":              "Valério Máximo",
    "Vitruvius Pollio":              "Vitrúvio",
    # ── formas curtas usadas pelo PHI Latin ──────────────────────────────────
    "Virgil":                        "Virgílio",
    "Cicero":                        "Cícero",
    "Caesar":                        "Júlio César",
    "Livy":                          "Tito Lívio",
    "Tacitus":                       "Tácito",
    "Seneca":                        "Sêneca",
    "Plautus":                       "Plauto",
    "Propertius":                    "Propércio",
    "Statius":                       "Estácio",
    "Florus":                        "Floro",
    "Velleius Paterculus":           "Veleo Paterculo",
    "Pliny the Elder":               "Plínio, o Velho",
    "Pliny the Younger":             "Plínio, o Jovem",
    "Ammianus Marcellinus":          "Amiano Marcelino",
}

# ── títulos de obras ───────────────────────────────────────────────────────────

OBRAS_PT: dict[str, str] = {
    # Épicas / Poesia
    "Iliad":                         "Ilíada",
    "Odyssey":                       "Odisseia",
    "Aeneid":                        "Eneida",
    "Theogony":                      "Teogonia",
    "Works and Days":                "Os Trabalhos e os Dias",
    "Shield of Heracles":            "Escudo de Héracles",
    "Homeric Hymns":                 "Hinos Homéricos",
    "Argonautica":                   "Argonáutica",
    "Fall of Troy":                  "A Queda de Troia",
    "Daphnis and Chloe":             "Dáfnis e Cloé",
    "Ephesiaca":                     "Efesíacas",
    "Aethiopica":                    "Etiópicas",
    # Historiadores
    "Histories":                     "Histórias",
    "History":                       "Histórias",
    "History of the Peloponnesian War": "História da Guerra do Peloponeso",
    "Anabasis":                      "Anábase",
    "Hellenica":                     "Helênicas",
    "Annals":                        "Anais",
    "Histories (Tacitus)":           "Histórias",
    "Germania":                      "Germânia",
    "Agricola":                      "Ágricola",
    "Ab urbe condita":               "Ab Urbe Condita",
    "Gallic Wars":                   "Guerra das Gálias",
    "Gallic War":                    "Guerra das Gálias",
    "Civil Wars":                    "Guerras Civis",
    "Civil War":                     "Guerra Civil",
    "Historical Library":            "Biblioteca Histórica",
    "Library":                       "Biblioteca",
    "Description of Greece":         "Descrição da Grécia",
    "Geography":                     "Geografia",
    "Antiquitates Romanae":          "Antiguidades Romanas",
    "Indica":                        "Indica",
    "Periplus Ponti Euxini":         "Périplo do Ponto Euxino",
    # Filosofia Platônica
    "Republic":                      "República",
    "Laws":                          "Leis",
    "Apology":                       "Apologia",
    "Symposium":                     "Banquete",
    "Banquet":                       "Banquete",
    "Phaedo":                        "Fédon",
    "Phaedrus":                      "Fedro",
    "Meno":                          "Mênon",
    "Timaeus":                       "Timeu",
    "Parmenides":                    "Parmênides",
    "Sophist":                       "Sofista",
    "Statesman":                     "O Político",
    "Theaetetus":                    "Teeteto",
    "Critias":                       "Crítias",
    "Protagoras":                    "Protágoras",
    "Gorgias":                       "Górgia",
    "Cratylus":                      "Crátilo",
    "Charmides":                     "Cármides",
    "Laches":                        "Laques",
    "Euthyphro":                     "Êutífron",
    "Philebus":                      "Filebo",
    "Ion":                           "Íon",
    "Lysis":                         "Lisis",
    "Menexenus":                     "Menêxeno",
    "Euthydemus":                    "Eutidemo",
    "Epinomis":                      "Epínomis",
    "Alcibiades 1":                  "Alcibíades I",
    "Alcibiades 2":                  "Alcibíades II",
    "Hippias Major":                 "Hípias Maior",
    "Hippias Minor":                 "Hípias Menor",
    "Lovers":                        "Os Amantes",
    "Cleitophon":                    "Clitofonte",
    "Minos":                         "Minos",
    # Filosofia Aristotélica
    "Nicomachean Ethics":            "Ética a Nicômaco",
    "Politics":                      "Política",
    "Poetics":                       "Poética",
    "On the Soul":                   "Sobre a Alma",
    # Outros Filósofos
    "Discourses":                    "Discursos",
    "Meditations":                   "Meditações",
    "Consolation of Philosophy":     "Consolação da Filosofia",
    "Economics":                     "Econômico",
    "Memorabilia":                   "Memoráveis",
    "Cyropaedia":                    "Ciropedia",
    "Characters":                    "Caracteres",
    "On the Sublime":                "Sobre o Sublime",
    # Oratória / Retórica
    "Against Vatinius":              "Contra Vatínio",
    "Against Verres":                "Contra Verres",
    "Against Catiline":              "Contra Catilina",
    "Against Ctesiphon":             "Contra Ctesifonte",
    "Against Demosthenes":           "Contra Demóstenes",
    "Against Leocrates":             "Contra Leócrates",
    "Against Leptines":              "Contra Léptines",
    "Against Meidias":               "Contra Mídias",
    "Against Timarchus":             "Contra Timárco",
    "Against the Sophists":          "Contra os Sofistas",
    "On the Crown":                  "Sobre a Coroa",
    "On the Embassy":                "Sobre a Embaixada",
    "On the False Embassy":          "Sobre a Falsa Embaixada",
    "On the Mysteries":              "Sobre os Mistérios",
    "On His Return":                 "Sobre o Seu Regresso",
    "On the Peace":                  "Sobre a Paz",
    "On the Peace with Sparta":      "Sobre a Paz com Esparta",
    "On the Chersonese":             "Sobre o Quersoneso",
    "On the Murder of Eratosthenes": "Sobre o Assassinato de Eratóstenes",
    "Philippics":                    "Filípicas",
    "Philippic 1":                   "Filípica I",
    "Philippic 2":                   "Filípica II",
    "Philippic 3":                   "Filípica III",
    "Philippic 4":                   "Filípica IV",
    "Letters":                       "Cartas",
    "Epistles":                      "Epístolas",
    "Letters to Atticus":            "Cartas a Ático",
    "Letters to Friends":            "Cartas a Amigos",
    "Letters to his Friends":        "Cartas aos Amigos",
    "Letters to Brutus":             "Cartas a Bruto",
    "Letters to his brother Quintus": "Cartas ao Irmão Quinto",
    "Institutes of Oratory":         "Instituição Oratória",
    "On Oratory":                    "Sobre a Oratória",
    "Funeral Oration":               "Discurso Fúnebre",
    "Antidosis":                     "Antidose",
    "Panegyricus":                   "Panegírico",
    "Archidamus":                    "Arquidamo",
    "Areopagiticus":                 "Areiopagítico",
    # Poesia Latina
    "Odes":                          "Odes",
    "Epodes":                        "Epodos",
    "Satires":                       "Sátiras",
    "Ars Poetica":                   "Arte Poética",
    "Carmen Saeculare":              "Canto Secular",
    "Metamorphoses":                 "Metamorfoses",
    "Ars Amatoria":                  "Arte de Amar",
    "Amores":                        "Amores",
    "Fasti":                         "Fasti",
    "Tristia":                       "Tristezas",
    "Heroides":                      "Heróidas",
    "Elegies":                       "Elegias",
    "Thebaid":                       "Tebaida",
    "Pharsalia":                     "Farsália",
    "Eclogues":                      "Éclogas",
    "Georgics":                      "Geórgicas",
    # Teatro Grego
    "Oedipus Rex":                   "Édipo Rei",
    "Oedipus Tyrannus":              "Édipo Rei",
    "Oedipus at Colonus":            "Édipo em Colono",
    "Antigone":                      "Antígona",
    "Electra":                       "Electra",
    "Ajax":                          "Ájax",
    "Philoctetes":                   "Filoctetes",
    "Trachiniae":                    "As Traquínias",
    "Seven Against Thebes":          "Sete contra Tebas",
    "Persians":                      "Os Persas",
    "Agamemnon":                     "Agamêmnon",
    "Libation Bearers":              "Coéforas",
    "Eumenides":                     "Eumênides",
    "Prometheus Bound":              "Prometeu Acorrentado",
    "Supplices":                     "Suplicantes",
    "The Suppliant Maidens":         "As Suplicantes",
    "Medea":                         "Medeia",
    "Bacchae":                       "Bacantes",
    "Alcestis":                      "Alceste",
    "Andromache":                    "Andrômaca",
    "Cyclops":                       "Ciclope",
    "Hecuba":                        "Hécuba",
    "Helen":                         "Helena",
    "Heracles":                      "Héracles",
    "Hercules":                      "Héracles",
    "Heracleidae":                   "Heráclidas",
    "Iphigenia in Aulis":            "Ifigênia em Áulide",
    "Iphigenia in Tauris":           "Ifigênia entre os Tauros",
    "Orestes":                       "Orestes",
    "Phoenissae":                    "Fenícias",
    "Rhesus":                        "Reso",
    "The Trojan Women":              "As Troianas",
    "Lysistrata":                    "Lisístrata",
    "Knights":                       "Cavaleiros",
    "Wealth":                        "Pluto",
    "Peace":                         "A Paz",
    "Clouds":                        "As Nuvens",
    "Frogs":                         "As Rãs",
    "Birds":                         "As Aves",
    "Wasps":                         "As Vespas",
    # Teatro Latino
    "Brothers":                      "Os Irmãos",
    "Andria":                        "A Andriana",
    # Ciência / Técnica
    "Natural History":               "História Natural",
    "Naturalis Historia":            "História Natural",
    "On the Nature of Things":       "Sobre a Natureza das Coisas",
    "Elements":                      "Elementos",
    "Almagest":                      "Almagesto",
    "On Architecture":               "Sobre a Arquitetura",
    "On Agriculture":                "Sobre a Agricultura",
    "On Hunting":                    "Sobre a Caça",
    "On the Art of Horsemanship":    "Sobre a Arte da Equitação",
    "On the Cavalry Commander":      "Sobre o Comandante de Cavalaria",
    "Ways and Means":                "Poroi (Rendas)",
    "Constitution of the Lacedaimonians": "Constituição dos Lacedemônios",
    # Bíblia / Novo Testamento
    "New Testament":                 "Novo Testamento",
    "Gospel of Matthew":             "Evangelho de Mateus",
    "Gospel of Mark":                "Evangelho de Marcos",
    "Gospel of Luke":                "Evangelho de Lucas",
    "Gospel of John":                "Evangelho de João",
    "Gospel according to Matthew":   "Evangelho de Mateus",
    "Gospel according to Luke":      "Evangelho de Lucas",
    "Gospel according to John":      "Evangelho de João",
    "Acts of the Apostles":          "Atos dos Apóstolos",
    "Revelation":                    "Apocalipse",
    "Book of Revelation":            "Apocalipse",
    "Book of James":                 "Epístola de Tiago",
    "Epistle of Jude":               "Epístola de Judas",
    "Epistle to the Hebrews":        "Epístola aos Hebreus",
    "The Epistle of Barnabas":       "Epístola de Barnabé",
    "Letter to the Colossians":      "Carta aos Colossenses",
    "Letter to the Ephesians":       "Carta aos Efésios",
    "Letter to the Galatians":       "Carta aos Gálatas",
    "Letter of Paul to Philemon":    "Carta de Paulo a Filemom",
    "Letter of Paul to Titus":       "Carta de Paulo a Tito",
    "Letter to the Philippians":     "Carta aos Filipenses",
    "Letter to the Romans":          "Carta aos Romanos",
    "First Letter of John":          "Primeira Carta de João",
    "Second Letter of John":         "Segunda Carta de João",
    "Third Letter of John":          "Terceira Carta de João",
    "First Letter of Peter":         "Primeira Carta de Pedro",
    "Second Letter of Peter":        "Segunda Carta de Pedro",
    "First Letter to Timothy":       "Primeira Carta a Timóteo",
    "Second Letter to Timothy":      "Segunda Carta a Timóteo",
    "First Letter to the Corinthians":  "Primeira Carta aos Coríntios",
    "Second Letter to the Corinthians": "Segunda Carta aos Coríntios",
    "First Letter to the Thessalonians":  "Primeira Carta aos Tessalonicenses",
    "Second Letter to the Thessalonians": "Segunda Carta aos Tessalonicenses",
    "Dialogue with Trypho":          "Diálogo com Trifão",
    # Plutarco — Vidas Paralelas (comparações)
    "Lives":                         "Vidas Paralelas",
    "Lives of the Twelve Caesars":   "Vida dos Doze Césares",
    "Comparison of Agesilaus and Pompey":          "Comparação de Agesilau e Pompeu",
    "Comparison of Agis and Cleomenes and the Gracchi": "Comparação de Ágis e Cleômenes com os Gracos",
    "Comparison of Alcibiades and Coriolanus":     "Comparação de Alcibíades e Coriolano",
    "Comparison of Aristides and Marcus Cato":     "Comparação de Aristides e Marco Catão",
    "Comparison of Demetrius and Antony":          "Comparação de Demétrio e António",
    "Comparison of Demosthenes and Cicero":        "Comparação de Demóstenes e Cícero",
    "Comparison of Dion and Brutus":               "Comparação de Díon e Bruto",
    "Comparison of Lucullus and Cimon":            "Comparação de Lúculo e Cimon",
    "Comparison of Lycurgus and Numa":             "Comparação de Licurgo e Numa",
    "Comparison of Lysander and Sulla":            "Comparação de Lisandro e Sila",
    "Comparison of Nicias and Crassus":            "Comparação de Nícias e Crasso",
    "Comparison of Pelopidas and Marcellus":       "Comparação de Pelópidas e Marcelo",
    "Comparison of Pericles and Fabius Maximus":   "Comparação de Péricles e Fábio Máximo",
    "Comparison of Philopoemen and Titus":         "Comparação de Filópemem e Tito",
    "Comparison of Sertorius and Eumenes":         "Comparação de Sertório e Êumenes",
    "Comparison of Solon and Publicola":           "Comparação de Sólon e Publícola",
    "Comparison of Theseus and Romulus":           "Comparação de Teseu e Rômulo",
    "Comparison of Timoleon and Aemilius":         "Comparação de Timoleão e Emílio",
    # Outros
    "Satyricon":                     "Satyricon",
    "Dialogue with Trypho":          "Diálogo com Trifão",
    # Xenofonte — obras menores
    "Hiero":                         "Hierão",
    "Agesilaus":                     "Agesilau",
    # Antifonte / Lísias — discursos específicos
    "Against the Stepmother for Poisoning": "Contra a Madrasta por Envenenamento",
    "On the Choreutes":              "Sobre o Coreuta",
    "On the murder of Herodes":      "Sobre o Assassinato de Herodes",
    "On the Murder of Eratosthenes": "Sobre o Assassinato de Eratóstenes",
    "Against Eratosthenes, who had been One of the Thirty: Spoken by Lysias Himself":
        "Contra Eratóstenes (um dos Trinta)",
    # Andócides
    "Against Alcibiades":            "Contra Alcibíades",
    # Discursos de Demóstenes
    "Against Androtion":             "Contra Androtion",
    "Against Aphobus I":             "Contra Aphobus I",
    "Against Aphobus II":            "Contra Aphobus II",
    "Against Aphobus III":           "Contra Aphobus III",
    "Against Aristocrates":          "Contra Aristocrates",
    "Against Aristogeiton I":        "Contra Aristogíton I",
    "Against Aristogeiton II":       "Contra Aristogíton II",
    "Against Boeotus I":             "Contra Beoto I",
    "Against Boeotus II":            "Contra Beoto II",
    "Against Callicles":             "Contra Cálicles",
    "Against Conon":                 "Contra Conon",
    "Against Dionysodorus":          "Contra Dionisodoro",
    "Against Eubulides":             "Contra Êubúlides",
    "Against Evergus and Mnesibulus": "Contra Évergos e Mnesíbulo",
    "Against Lacritus":              "Contra Lácritos",
    "Against Leochares":             "Contra Leócares",
    "Against Macartatus":            "Contra Macártato",
    "Against Nausimachus and Xenopeithes": "Contra Nausímaco e Xenopeites",
    "Against Olympiodorus":          "Contra Olimpiodoro",
    "Against Onetor I":              "Contra Onetor I",
    "Against Onetor II":             "Contra Onetor II",
    "Against Pantaenetus":           "Contra Pantêneto",
    "Against Phaenippus":            "Contra Fenipo",
    "Against Phormio":               "Contra Fórmio",
    "Against Simon":                 "Contra Simão",
    "Against Spudias":               "Contra Espúdias",
    "Against Stephanus I":           "Contra Estêfano I",
    "Against Stephanus II":          "Contra Estêfano II",
    "Against Timocrates":            "Contra Timócrates",
    "Against Zenothemis":            "Contra Zenotêmis",
    "Against The Corn-Dealers":      "Contra os Comerciantes de Grãos",
    "Against The Subversion of the Ancestral Constitution of Athens":
        "Contra a Subversão da Constituição Ancestral de Atenas",
    "Against Theocrines":            "Contra Teócrines",
    "Against Philippides":           "Contra Filípides",
    "Against Callimac… ":            "Contra Calímaco",
    "Against Philocrates: Supplementary": "Contra Filócrates",
    "Against Epicrates and his Fellow-envoys: Supplementary": "Contra Epicrates e seus Co-embaixadores",
    "Against Ergocles: Supplementary": "Contra Êrgocles",
    # Isócrates
    "Nicocles or the Cyprians":      "Nicocles ou os Cipriotas",
    "To Nicocles":                   "A Nicocles",
    "To Demonicus":                  "A Demónico",
    "Evagoras":                      "Evágoras",
    "Busiris":                       "Busíris",
    # Discursos de Lísias (específicos)
    "On Behalf of Euphiletus":       "Em Defesa de Eufíleto",
    "For Polystratus":               "Em Defesa de Polistrato",
    "For Callias":                   "Em Defesa de Cálias",
    "For Phormio":                   "Em Defesa de Fórmio",
    "For The Soldier":               "Em Defesa do Soldado",
    "For the Liberty of the Rhodians": "Pela Liberdade dos Ródios",
    "For the People of Megalopolis": "Pelo Povo de Megalópolis",
    # Hipérides
    "In Defence of Euxenippus":      "Em Defesa de Euxênipo",
    "In Defence of Lycophron":       "Em Defesa de Licofrão",
    # Antifonte
    "The First Tetralogy":           "Primeira Tetralogia",
    "The Second Tetralogy":          "Segunda Tetralogia",
    "The Third Tetralogy":           "Terceira Tetralogia",
}


import re as _re

# Sufixos ordinais para "First/Second/Third … to/of"
_ORDINAL_PT = {"First": "Primeira", "Second": "Segunda", "Third": "Terceira",
               "Fourth": "Quarta", "Fifth": "Quinta"}

# Padrões automáticos: (regex, substituição PT)
_PADROES: list[tuple] = [
    # "Against X"  → "Contra X"
    (_re.compile(r'^Against (.+)$'), lambda m: f'Contra {m.group(1)}'),
    # "On the X" / "On His X" / "On X"
    (_re.compile(r'^On the (.+)$'), lambda m: f'Sobre {m.group(1)}'),
    (_re.compile(r'^On His (.+)$'), lambda m: f'Sobre Seu/Sua {m.group(1)}'),
    (_re.compile(r'^On (.+)$'),     lambda m: f'Sobre {m.group(1)}'),
    # "For X" (discurso de defesa)
    (_re.compile(r'^For (.+)$'),    lambda m: f'Em Defesa de {m.group(1)}'),
    # "In Defence of X"
    (_re.compile(r'^In Defen[cs]e of (.+)$'), lambda m: f'Em Defesa de {m.group(1)}'),
    # "In Defense Against …"
    (_re.compile(r'^Defense Against (.+)$'), lambda m: f'Defesa Contra {m.group(1)}'),
    # "Concerning X"
    (_re.compile(r'^Concerning (.+)$'), lambda m: f'Sobre {m.group(1)}'),
    # "Before the X"
    (_re.compile(r'^Before (.+)$'), lambda m: f'Perante {m.group(1)}'),
    # "Comparison of X" → "Comparação de X"
    (_re.compile(r'^Comparison of (.+)$'), lambda m: f'Comparação de {m.group(1)}'),
    # "Answer to X"
    (_re.compile(r'^Answer to (.+)$'), lambda m: f'Resposta a {m.group(1)}'),
    # "Letter to the X" / "Letter of Paul to X"
    (_re.compile(r'^Letter of (\w+) to (.+)$'), lambda m: f'Carta de {m.group(1)} a {m.group(2)}'),
    (_re.compile(r'^Letter to the (.+)$'), lambda m: f'Carta aos {m.group(1)}'),
    (_re.compile(r'^Letter to (.+)$'),     lambda m: f'Carta a {m.group(1)}'),
    # "First/Second/Third Letter to/of X"
    (_re.compile(r'^(First|Second|Third|Fourth) Letter to the (.+)$'),
        lambda m: f'{_ORDINAL_PT[m.group(1)]} Carta aos {m.group(2)}'),
    (_re.compile(r'^(First|Second|Third|Fourth) Letter to (.+)$'),
        lambda m: f'{_ORDINAL_PT[m.group(1)]} Carta a {m.group(2)}'),
    (_re.compile(r'^(First|Second|Third|Fourth) Letter of (.+)$'),
        lambda m: f'{_ORDINAL_PT[m.group(1)]} Carta de {m.group(2)}'),
    # "Epistle to X"
    (_re.compile(r'^Epistle to the (.+)$'), lambda m: f'Epístola aos {m.group(1)}'),
    (_re.compile(r'^Epistle to (.+)$'),     lambda m: f'Epístola a {m.group(1)}'),
    (_re.compile(r'^Epistle of (.+)$'),     lambda m: f'Epístola de {m.group(1)}'),
    # "Gospel according to X"
    (_re.compile(r'^Gospel according to (.+)$'), lambda m: f'Evangelho de {m.group(1)}'),
    (_re.compile(r'^Gospel of (.+)$'),           lambda m: f'Evangelho de {m.group(1)}'),
]


def traduzir_autor(nome: str) -> str:
    """Retorna a tradução PT do nome do autor, ou o original se não constar."""
    return AUTORES_PT.get(nome, nome)


def traduzir_obra(titulo: str) -> str:
    """Retorna a tradução PT do título da obra.
    Primeiro verifica o dicionário exacto; depois tenta os padrões automáticos."""
    if titulo in OBRAS_PT:
        return OBRAS_PT[titulo]
    for pat, repl in _PADROES:
        m = pat.match(titulo)
        if m:
            return repl(m)
    return titulo


def traduzir_entrada(entrada: dict) -> dict:
    """
    Recebe um dict de catálogo Perseus/PHI/LL e devolve cópia com
    'autor', 'obra' e 'display' traduzidos para PT quando disponível.
    """
    d = dict(entrada)
    autor_orig = d.get("autor", "")
    obra_orig  = d.get("obra",  "")
    autor_pt   = traduzir_autor(autor_orig)  if autor_orig else autor_orig
    obra_pt    = traduzir_obra(obra_orig)    if obra_orig  else obra_orig

    if autor_orig or obra_orig:
        d["autor"] = autor_pt
        d["obra"]  = obra_pt
        if autor_pt and obra_pt:
            d["display"] = f"{autor_pt} — {obra_pt}"
        elif autor_pt:
            d["display"] = autor_pt
        elif obra_pt:
            d["display"] = obra_pt

    return d


def traduzir_catalogo(catalogo: list[dict]) -> list[dict]:
    """Aplica traduzir_entrada a todos os itens do catálogo."""
    return [traduzir_entrada(e) for e in catalogo]
